/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rolandhe_gm_Resizer */

#ifndef _Included_com_github_rolandhe_gm_Resizer
#define _Included_com_github_rolandhe_gm_Resizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rolandhe_gm_Resizer
 * Method:    thumbnailImage
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_Resizer_thumbnailImage
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_github_rolandhe_gm_Resizer
 * Method:    scaleImage
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_Resizer_scaleImage
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_github_rolandhe_gm_Resizer
 * Method:    sampleImage
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_Resizer_sampleImage
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_github_rolandhe_gm_Resizer
 * Method:    resizeImage
 * Signature: (JJJID)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_Resizer_resizeImage
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
