/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rolandhe_gm_GmBase */

#ifndef _Included_com_github_rolandhe_gm_GmBase
#define _Included_com_github_rolandhe_gm_GmBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rolandhe_gm_GmBase
 * Method:    initGmLib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_GmBase_initGmLib
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
