/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rolandhe_gm_Transformer */

#ifndef _Included_com_github_rolandhe_gm_Transformer
#define _Included_com_github_rolandhe_gm_Transformer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rolandhe_gm_Transformer
 * Method:    cropImage
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_Transformer_cropImage
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_github_rolandhe_gm_Transformer
 * Method:    chopImage
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_Transformer_chopImage
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_github_rolandhe_gm_Transformer
 * Method:    extentImage
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_Transformer_extentImage
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_github_rolandhe_gm_Transformer
 * Method:    coalesceImages
 * Signature: ([J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_Transformer_coalesceImages
  (JNIEnv *, jclass, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
