/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rolandhe_gm_Composite */

#ifndef _Included_com_github_rolandhe_gm_Composite
#define _Included_com_github_rolandhe_gm_Composite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rolandhe_gm_Composite
 * Method:    compositeImage
 * Signature: (JIJJJ)I
 */
JNIEXPORT jboolean JNICALL Java_com_github_rolandhe_gm_Composite_compositeImage
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jlong);

/*
 * Class:     com_github_rolandhe_gm_Composite
 * Method:    appendImages
 * Signature: ([JI)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_Composite_appendImages
  (JNIEnv *, jclass, jlongArray, jint);

/*
 * Class:     com_github_rolandhe_gm_Composite
 * Method:    writeImages
 * Signature: (J[JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_rolandhe_gm_Composite_writeImages
  (JNIEnv *, jclass, jlong, jlongArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_rolandhe_gm_Composite_CompositeOperator */

#ifndef _Included_com_github_rolandhe_gm_Composite_CompositeOperator
#define _Included_com_github_rolandhe_gm_Composite_CompositeOperator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
