/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rolandhe_gm_Shear */

#ifndef _Included_com_github_rolandhe_gm_Shear
#define _Included_com_github_rolandhe_gm_Shear
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rolandhe_gm_Shear
 * Method:    rotateImage
 * Signature: (JD)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_Shear_rotateImage
  (JNIEnv *, jclass, jlong, jdouble);

#ifdef __cplusplus
}
#endif
#endif
