/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rolandhe_gm_DrawInfo */

#ifndef _Included_com_github_rolandhe_gm_DrawInfo
#define _Included_com_github_rolandhe_gm_DrawInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    cloneDrawInfo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_DrawInfo_cloneDrawInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    destroyDrawInfo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_DrawInfo_destroyDrawInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    setBoxColor
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_DrawInfo_setBoxColor
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    setDecorate
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_DrawInfo_setDecorate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    setDensity
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_DrawInfo_setDensity
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    setFill
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_DrawInfo_setFill
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    setFont
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_DrawInfo_setFont
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    setPointsize
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_DrawInfo_setPointsize
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    setGravity
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_DrawInfo_setGravity
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    setPrimitive
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_DrawInfo_setPrimitive
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_rolandhe_gm_DrawInfo
 * Method:    setText
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_DrawInfo_setText
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_rolandhe_gm_DrawInfo_GravityType */

#ifndef _Included_com_github_rolandhe_gm_DrawInfo_GravityType
#define _Included_com_github_rolandhe_gm_DrawInfo_GravityType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_github_rolandhe_gm_DrawInfo_DecorationType */

#ifndef _Included_com_github_rolandhe_gm_DrawInfo_DecorationType
#define _Included_com_github_rolandhe_gm_DrawInfo_DecorationType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
