/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rolandhe_gm_ImageProcessor */

#ifndef _Included_com_github_rolandhe_gm_ImageProcessor
#define _Included_com_github_rolandhe_gm_ImageProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rolandhe_gm_ImageProcessor
 * Method:    obtainTypeMetrics
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_ImageProcessor_obtainTypeMetrics
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_rolandhe_gm_ImageProcessor
 * Method:    annotateImage
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_rolandhe_gm_ImageProcessor_annotateImage
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_github_rolandhe_gm_ImageProcessor
 * Method:    transparentImage
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_rolandhe_gm_ImageProcessor_transparentImage
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_github_rolandhe_gm_ImageProcessor
 * Method:    drawTextOnImage
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_rolandhe_gm_ImageProcessor_drawTextOnImage
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
