/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rolandhe_gm_ImageInfo */

#ifndef _Included_com_github_rolandhe_gm_ImageInfo
#define _Included_com_github_rolandhe_gm_ImageInfo
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_rolandhe_gm_ImageInfo_MAGICK_TRUE
#define com_github_rolandhe_gm_ImageInfo_MAGICK_TRUE 1L
#undef com_github_rolandhe_gm_ImageInfo_MAGICK_FALSE
#define com_github_rolandhe_gm_ImageInfo_MAGICK_FALSE 0L
/*
 * Class:     com_github_rolandhe_gm_ImageInfo
 * Method:    cloneImageInfo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_rolandhe_gm_ImageInfo_cloneImageInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_rolandhe_gm_ImageInfo
 * Method:    destroyImageInfo
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_ImageInfo_destroyImageInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_rolandhe_gm_ImageInfo
 * Method:    setupFormat
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_ImageInfo_setupFormat
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_rolandhe_gm_ImageInfo
 * Method:    setupFileName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_ImageInfo_setupFileName
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_github_rolandhe_gm_ImageInfo
 * Method:    setupAdjoin
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_ImageInfo_setupAdjoin
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
