/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rolandhe_gm_TypeMetric */

#ifndef _Included_com_github_rolandhe_gm_TypeMetric
#define _Included_com_github_rolandhe_gm_TypeMetric
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rolandhe_gm_TypeMetric
 * Method:    getWidth
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_rolandhe_gm_TypeMetric_getWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_rolandhe_gm_TypeMetric
 * Method:    getHeight
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_rolandhe_gm_TypeMetric_getHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_rolandhe_gm_TypeMetric
 * Method:    getAscent
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_rolandhe_gm_TypeMetric_getAscent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_rolandhe_gm_TypeMetric
 * Method:    getDescent
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_github_rolandhe_gm_TypeMetric_getDescent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_rolandhe_gm_TypeMetric
 * Method:    destoryTypeMetric
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_rolandhe_gm_TypeMetric_destoryTypeMetric
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
